{
 "title": "Shadowsocks",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ss-server1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"ss-server1\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ss-server2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"ss-server2\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ss-server3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"ss-server3\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Haproxy",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"my-haproxy\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "警告清單", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 } }
 ]
}